version: '3'

vars:
  APP_NAME:
    sh: grep -E '^module ' go.mod 2>/dev/null | awk '{print $2}' || echo "somegoapp"
  OUTPUT_DIR: bin
  MAIN_FILE: main.go
  GOMOD_EXISTS:
    sh: '[ -f go.mod ] && echo "yes" || echo "no"'
  GOARCH:
    sh: |
      if [ -n "$GOARCH" ]; then
        echo "$GOARCH"
      else
        arch=$(dpkg --print-architecture 2>/dev/null || rpm --eval %{_arch} 2>/dev/null || echo "unknown")
        if [ "$arch" = "unknown" ]; then
          arch=$(uname -m)
        fi
        if [ "$arch" = "x86_64" ]; then
          arch="amd64"
        fi
        if [ "$arch" = "unknown" ]; then
          arch="arm64"
        fi
        echo "$arch"
      fi
  VERSION:
    sh: |
      if git diff --cached --quiet 2>/dev/null; then
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        latest_commit=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
        if git describe --tags --exact-match HEAD >/dev/null 2>&1; then
          echo "$latest_tag"
        else
          echo "${latest_tag}-${latest_commit}_dev"
        fi
      else
        echo "9999_currentDEV"
      fi
  OS_NAME:
    sh: uname -s

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  check-go-mod:
    desc: Check if go.mod exists
    internal: true
    silent: true
    cmds:
      - |
        if [ "{{.GOMOD_EXISTS}}" = "no" ]; then
          echo "Warning: Project is not initialized yet (missing go.mod)."
          echo "Run 'task init PROJECTNAME=<your_project_name>' to initialize the project."
          exit 1
        fi

  init:
    desc: "Initialize Go project (usage: task init PROJECTNAME=<name>)"
    cmds:
      - |
        if [ -z "{{.PROJECTNAME}}" ]; then
          echo "Error: PROJECTNAME is not supplied. Usage: task init PROJECTNAME=<your_project_name>"
          exit 1
        fi
        echo "Initializing Go project with name '{{.PROJECTNAME}}'..."
        go mod init {{.PROJECTNAME}}
        go mod tidy
        echo "Project initialized successfully."

  prepare:
    desc: Download and install dependencies
    deps: [check-go-mod]
    cmds:
      - echo "Downloading dependencies..."
      - go mod download
      - echo "Dependencies downloaded."

  lin-dep-ubuntu:
    desc: Install local dependencies for Linux build on Ubuntu
    cmds:
      - |
        sudo apt-get update && sudo apt-get install -y \
          libgl1-mesa-dev \
          libx11-dev \
          xorg-dev \
          libxcursor-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxi-dev \
          libglu1-mesa-dev \
          pkg-config

  win-dep-ubuntu:
    desc: Install local dependencies for Windows build on Ubuntu
    cmds:
      - sudo apt-get update && sudo apt-get install -y gcc-mingw-w64-x86-64 libgl1-mesa-dev xorg-dev libgtk-3-dev

  build:
    desc: Build the application for the current architecture
    deps: [prepare]
    cmds:
      - |
        echo "Current OS ({{.OS_NAME}}) architecture ({{.GOARCH}})..."
        case "{{.OS_NAME}}" in
          Linux)
            task build-linux
            ;;
          Darwin)
            task build-mac
            ;;
          MINGW64_NT*|MSYS_NT*)
            task build-windows
            ;;
          *)
            echo "Unsupported operating system: {{.OS_NAME}}"
            exit 1
            ;;
        esac

  build-linux:
    desc: Build for Linux
    deps: [prepare]
    cmds:
      - echo "Building for Linux..."
      - echo "GOOS=linux GOARCH={{.GOARCH}} go build -ldflags \"-X main.Version={{.VERSION}}\" -o {{.OUTPUT_DIR}}/{{.APP_NAME}}-{{.VERSION}}_linux_{{.GOARCH}} {{.MAIN_FILE}}"
      - GOOS=linux GOARCH={{.GOARCH}} go build -ldflags "-X main.Version={{.VERSION}}" -o {{.OUTPUT_DIR}}/{{.APP_NAME}}-{{.VERSION}}_linux_{{.GOARCH}} {{.MAIN_FILE}}
      - echo "Linux build completed {{.OUTPUT_DIR}}/{{.APP_NAME}}-{{.VERSION}}_linux_{{.GOARCH}}"

  build-mac:
    desc: Build for macOS (not tested)
    deps: [prepare]
    cmds:
      - echo "Building for macOS (not tested)..."
      - GOOS=darwin GOARCH={{.GOARCH}} go build -ldflags "-X main.Version={{.VERSION}}" -o {{.OUTPUT_DIR}}/{{.APP_NAME}}-{{.VERSION}}_mac_{{.GOARCH}} {{.MAIN_FILE}}
      - echo "macOS build completed {{.OUTPUT_DIR}}/{{.APP_NAME}}-{{.VERSION}}_mac_{{.GOARCH}}"

  build-windows:
    desc: Build for Windows
    deps: [prepare]
    cmds:
      - echo "Building for Windows..."
      - GOOS=windows GOARCH={{.GOARCH}} CGO_ENABLED=1 CC="x86_64-w64-mingw32-gcc" CXX="x86_64-w64-mingw32-g++" go build -ldflags "-X main.Version={{.VERSION}}" -o {{.OUTPUT_DIR}}/{{.APP_NAME}}-{{.VERSION}}_windows_{{.GOARCH}}.exe {{.MAIN_FILE}}
      - echo "Windows build completed {{.OUTPUT_DIR}}/{{.APP_NAME}}-{{.VERSION}}_windows_{{.GOARCH}}.exe"

  build-docker-windows:
    desc: Build Windows binary in Docker
    cmds:
      - echo "Building Windows binary in Docker..."
      - DOCKER_BUILDKIT=1 docker build --build-arg APP_NAME={{.APP_NAME}}-{{.VERSION}}_windows_{{.GOARCH}} -f Dockerfile.windows --output type=local,dest=./{{.OUTPUT_DIR}} .
      - echo "Windows Docker build completed:{{.OUTPUT_DIR}}/{{.APP_NAME}}-{{.VERSION}}_windows_{{.GOARCH}}.exe"

  build-docker-linux:
    desc: Build Linux binary in Docker
    cmds:
      - echo "Building Linux binary in Docker..."
      - DOCKER_BUILDKIT=1 docker build --build-arg APP_NAME={{.APP_NAME}}-{{.VERSION}}_linux_{{.GOARCH}} -f Dockerfile.linux --output type=local,dest=./{{.OUTPUT_DIR}} .
      - echo "Linux Docker build completed:{{.OUTPUT_DIR}}/{{.APP_NAME}}-{{.VERSION}}_linux_{{.GOARCH}}"

  build-all:
    desc: Build the application for all supported platforms
    deps: [prepare]
    cmds:
      - task: build-linux
      - task: build-windows
      - echo "All builds completed successfully!"

  release:
    desc: Create a new GitHub release with the built binaries (requires 'gh' CLI)
    deps: [build-all]
    cmds:
      - echo "Creating GitHub release for version {{.VERSION}}..."
      - |
        gh release create {{.VERSION}} \
          --title "Release {{.VERSION}}" \
          --notes "Semi-automated release for version {{.VERSION}}" \
          {{.OUTPUT_DIR}}/{{.APP_NAME}}-{{.VERSION}}_linux_{{.GOARCH}} \
          {{.OUTPUT_DIR}}/{{.APP_NAME}}-{{.VERSION}}_windows_{{.GOARCH}}.exe
      - echo "Release {{.VERSION}} created successfully."

  clean:
    desc: Remove build artifacts
    cmds:
      - echo "Cleaning up..."
      - rm -rf {{.OUTPUT_DIR}}
      - echo "Cleaned."

  recreate-mod:
    desc: Recreate go.mod and go.sum files
    cmds:
      - echo "Recreating go.mod and go.sum files..."
      - rm -f go.mod go.sum
      - go mod init your-module-name
      - go mod tidy
      - echo "go.mod and go.sum have been recreated successfully."

  format:
    desc: Format the source code
    cmds:
      - gofmt -s -w ./

  lint:
    desc: Lint the source code
    cmds:
      - golint

  test:
    desc: Run tests
    cmds:
      - go test -v

  info:
    desc: Show environment variables
    cmds:
      - echo "Environment Variables:"
      - echo "APP_NAME   {{.APP_NAME}}"
      - echo "VERSION    {{.VERSION}}"
      - echo "GOARCH     {{.GOARCH}}"
      - echo "OS_NAME    {{.OS_NAME}}"
      - echo "OUTPUT_DIR {{.OUTPUT_DIR}}"
      - echo "FILENAME   {{.APP_NAME}}-{{.VERSION}}_{{.OS_NAME}}_{{.GOARCH}}"
      - echo ""
      - echo "Hint You can override any variable when running task, e.g.,"
      - echo "      task build GOARCH=arm64"
